
linearVel : 0.3
angularVelocityRange : {
    start: -0.5,
    end: 0.5,
    step: 0.25
}

timeRange : {
    start: 0,
    end: 5,
    step: 0.5
}

wheelRadius : 0.033
wheelSeparation : 0.26


turtlebotBaseFrame : 'turtlebot/create::base'
